-- 复习卡片表
CREATE TABLE IF NOT EXISTS `review_card` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '卡片ID',
  `node_id` BIGINT NOT NULL COMMENT '知识点ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `question` TEXT COMMENT '问题',
  `answer` TEXT COMMENT '答案',
  `card_type` VARCHAR(20) NOT NULL DEFAULT 'simple' COMMENT '卡片类型：simple-简单, choice-单选题, fill-填空题',
  `difficulty` INT NOT NULL DEFAULT 1 COMMENT '难度：1-简单, 2-中等, 3-困难',
  `review_count` INT NOT NULL DEFAULT 0 COMMENT '复习次数',
  `correct_count` INT NOT NULL DEFAULT 0 COMMENT '正确次数',
  `incorrect_count` INT NOT NULL DEFAULT 0 COMMENT '错误次数',
  `average_accuracy` DECIMAL(5, 4) NOT NULL DEFAULT 0.0000 COMMENT '平均准确率',
  `mastery_level` INT NOT NULL DEFAULT 0 COMMENT '掌握程度：0-未掌握, 1-入门, 2-熟悉, 3-掌握, 4-精通, 5-专家',
  `memory_strength` DECIMAL(5, 4) NOT NULL DEFAULT 0.0000 COMMENT '记忆强度',
  `last_review_time` DATETIME COMMENT '最后复习时间',
  `next_review_time` DATETIME COMMENT '下次复习时间',
  `status` INT NOT NULL DEFAULT 0 COMMENT '状态：0-待复习, 1-已完成, 2-已跳过',
  `ai_generated` VARCHAR(10) NOT NULL DEFAULT 'false' COMMENT '是否AI生成：true-是, false-否',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` INT NOT NULL DEFAULT 0 COMMENT '删除标记：0-未删除, 1-已删除',
  INDEX `idx_user_id` (`user_id`),
  INDEX `idx_node_id` (`node_id`),
  INDEX `idx_next_review_time` (`next_review_time`),
  INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='复习卡片表';
