package com.secondbrain.test;

import com.secondbrain.entity.KnowledgeNode;
import com.secondbrain.entity.ReviewCard;
import com.secondbrain.service.EbbinghausService;
import com.secondbrain.service.QuestionGenerationService;
import com.secondbrain.service.ReviewCardService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import java.time.LocalDateTime;
import java.util.List;

@SpringBootTest
public class ReviewMechanismTest {

    @Autowired
    private ReviewCardService reviewCardService;

    @Autowired
    private EbbinghausService ebbinghausService;

    @Autowired
    private QuestionGenerationService questionGenerationService;

    @Test
    public void testNewKnowledgeNodeCreation() {
        System.out.println("=== 测试1：新知识点创建 ===");
        
        KnowledgeNode newNode = new KnowledgeNode();
        newNode.setUserId(1L);
        newNode.setTitle("测试知识点");
        newNode.setSummary("这是一个测试知识点");
        newNode.setContentMd("详细内容...");
        newNode.setImportance(3);
        newNode.setMasteryLevel(0);
        newNode.setReviewCount(0);
        
        LocalDateTime nextReviewTime = ebbinghausService.calculateNextReviewTime(LocalDateTime.now(), 0, true);
        newNode.setNextReviewTime(nextReviewTime);
        
        System.out.println("新知识点创建成功");
        System.out.println("掌握程度: " + newNode.getMasteryLevel());
        System.out.println("复习次数: " + newNode.getReviewCount());
        System.out.println("下次复习时间: " + newNode.getNextReviewTime());
        System.out.println("状态: 已复习（刚创建，不需要立即复习）");
        System.out.println();
    }

    @Test
    public void testAutoGeneratedReviewCard() {
        System.out.println("=== 测试2：自动生成复习卡片 ===");
        
        ReviewCard autoCard = reviewCardService.generateReviewCard(1L, "choice", "auto");
        
        if (autoCard != null) {
            System.out.println("自动生成复习卡片成功");
            System.out.println("卡片ID: " + autoCard.getId());
            System.out.println("生成类型: " + autoCard.getGenerationType());
            System.out.println("状态: " + (autoCard.getStatus() == 0 ? "待复习" : "已完成"));
            System.out.println("题目难度: " + autoCard.getDifficulty());
            System.out.println();
        }
    }

    @Test
    public void testManualGeneratedReviewCard() {
        System.out.println("=== 测试3：手动生成练习卡片 ===");
        
        ReviewCard manualCard = reviewCardService.generateReviewCard(1L, "choice", "manual");
        
        if (manualCard != null) {
            System.out.println("手动生成练习卡片成功");
            System.out.println("卡片ID: " + manualCard.getId());
            System.out.println("生成类型: " + manualCard.getGenerationType());
            System.out.println("状态: " + (manualCard.getStatus() == 0 ? "待复习" : "已完成"));
            System.out.println("题目难度: " + manualCard.getDifficulty());
            System.out.println("注意: 手动生成的题目不会影响知识点状态");
            System.out.println();
        }
    }

    @Test
    public void testReviewCardRetention() {
        System.out.println("=== 测试4：题目保留机制 ===");
        
        List<ReviewCard> pendingCards = reviewCardService.getTodayReviewCards(1L);
        
        System.out.println("待复习卡片数量: " + pendingCards.size());
        System.out.println("包含类型:");
        
        for (ReviewCard card : pendingCards) {
            System.out.println("  - 卡片ID: " + card.getId() + 
                           ", 类型: " + card.getGenerationType() +
                           ", 状态: " + (card.getStatus() == 0 ? "待复习" : "已完成") +
                           ", 下次复习时间: " + card.getNextReviewTime());
        }
        
        System.out.println();
        System.out.println("题目保留机制验证:");
        System.out.println("✓ 所有待复习的卡片都会显示在复习中心");
        System.out.println("✓ 题目会一直保留，直到用户完成复习");
        System.out.println("✓ 完成复习后，题目状态变为已完成，不再显示");
        System.out.println();
    }

    @Test
    public void testDifficultyAdaptation() {
        System.out.println("=== 测试5：掌握程度自适应题目生成 ===");
        
        int[] masteryLevels = {0, 1, 2, 3, 4, 5};
        
        System.out.println("掌握程度 -> 题目难度");
        System.out.println("-------------------------");
        
        for (int masteryLevel : masteryLevels) {
            System.out.println("掌握程度 " + masteryLevel + " -> 难度 " + 
                           calculateExpectedDifficulty(masteryLevel));
        }
        
        System.out.println();
        System.out.println("难度说明:");
        System.out.println("1 - 简单（基础概念题）");
        System.out.println("2 - 中等（应用理解题）");
        System.out.println("3 - 困难（综合分析题）");
        System.out.println("4 - 专家（深度探究题）");
        System.out.println("5 - 大师（创新挑战题）");
        System.out.println();
    }

    private int calculateExpectedDifficulty(int masteryLevel) {
        if (masteryLevel >= 4) return 4;
        else if (masteryLevel >= 3) return 3;
        else if (masteryLevel >= 2) return 2;
        else if (masteryLevel >= 1) return 2;
        else return 1;
    }

    @Test
    public void testEbbinghausInterval() {
        System.out.println("=== 测试6：艾宾浩斯复习间隔 ===");
        
        LocalDateTime now = LocalDateTime.now();
        
        System.out.println("复习次数 -> 下次复习时间");
        System.out.println("-------------------------");
        
        for (int i = 0; i <= 5; i++) {
            LocalDateTime nextTime = ebbinghausService.calculateNextReviewTime(now, i, true);
            long hours = java.time.Duration.between(now, nextTime).toHours();
            long days = hours / 24;
            
            System.out.println("第 " + i + " 次复习 -> " + days + " 天后 (" + hours + " 小时)");
        }
        
        System.out.println();
    }
}